filebeat.inputs:
- type: log
  enabled: true
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message
  paths:
    - /usr/share/filebeat/logs/my.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: http://kibana:5601
  username: '${ELK_USERNAME}'
  password: '${ELK_PASSWORD}'

output.logstash:
  hosts: ["logstash:5044"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: '${ELK_USERNAME}'
  password: '${ELK_PASSWORD}'
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"